
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // This block overwrites the datasource url-like attributes from
    // schema.prisma entirely, so directUrl has to be repeated here too - it's
    // not merged with schema.prisma's directUrl. Without it, `migrate deploy`
    // silently falls back to the pooled url for the advisory lock migrations
    // take, which hangs forever under Supabase's transaction-mode pooler.
    url: env("POSTGRES_PRISMA_URL"),
    directUrl: env("POSTGRES_URL_NON_POOLING"),
  },
});
